### ISSUE TITLE
setting checkboxes

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/LaunchCountdownEx#8] opened 2018-01-27 23:45 UTC
* The `sound enabled` checkbox doesn't "enabled" any sound.  
    `Kerbilized` set, `sound enabled`  — starts from 19s,
    `Kerbilized` set, `sound enabled` disabled  — starts from 15s.  

    So it behaves just like kottabos have described.  
    I think `sound enabled` doesn't describe that behavior, but renaming it to something like `limit to 15s` 
  and invert checkbox action does.

 * Should disabling `Abort execute` checkbox hide `Abort!` button? What it does?

**Comment by linuxgurugamer** [comment] 2018-01-28 03:39
When sound enabled is off (ie:   sound is disabled), it should start from 15 seconds, since there is no sound to play.
The bug is that it's playing sound  when it shouldn't

**Comment by yalov** [comment] 2018-01-28 13:49
Did you confirm the bug?

Shorter countdown with sound useful feature.

Оne of the sound in the set can be "None" (for no sound), and separate checkbox and slider for limit countdown

**Comment by linuxgurugamer** [comment] 2018-01-28 21:44
I confirmed it and have fixed it locally.
Right now I'm trying to see how I can stop the clock from closing after launch.  It's not a game breaker, so there isn't any rush to fix it

**Closed** 2018-11-20 03:59 UTC
